version: '3'

services:

  web:
    build: frontend
    volumes: 
      - frontend:/app/build

  api:
    build: api
    ports:
      - 8090:5000

  proxy: 
    image: nginx
    volumes:
      - frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    links:
      - api
    ports:
      - 5000:80

volumes:
  frontend: